const view=document.getElementById("view"),title=document.getElementById("viewTitle"),nav=document.getElementById("nav"),modal=document.getElementById("modal"),modalTitle=document.getElementById("modalTitle"),modalBody=document.getElementById("modalBody"),closeModal=document.getElementById("closeModal"),audioBtn=document.getElementById("audioBtn"),panicBtn=document.getElementById("panicBtn");
let audioOn=false;
const views={overview,combat,skills,gear,bio,principles,rules,party,ship,journal};
nav.addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;document.querySelectorAll(".nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");setView(b.dataset.view)});
closeModal.addEventListener("click",()=>modal.classList.add("hidden"));modal.addEventListener("click",e=>{if(e.target===modal)modal.classList.add("hidden")});
audioBtn.addEventListener("click",()=>{audioOn=!audioOn;audioBtn.textContent=`Audio ${audioOn?"On":"Off"}`;beep()});panicBtn.addEventListener("click",()=>{document.body.classList.toggle("red-alert");beep()});
function beep(){if(!audioOn)return;const c=new(window.AudioContext||window.webkitAudioContext)(),o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.055)}
function setView(name){title.textContent=name.charAt(0).toUpperCase()+name.slice(1);views[name]();beep()}
function pop(name,body){modalTitle.textContent=name;modalBody.innerHTML=body;modal.classList.remove("hidden")}
function overview(){view.innerHTML=`<div class="grid2"><div class="hero"></div><div class="card"><h3>${GAGE.name}</h3><div class="row"><span>Type</span><b>${GAGE.type}</b></div><div class="row"><span>Species</span><b>${GAGE.species}</b></div><div class="row"><span>Age</span><b>${GAGE.age}</b></div><div class="row"><span>Height</span><b>${GAGE.height}</b></div><div class="row"><span>Weight</span><b>${GAGE.weight}</b></div><div class="row"><span>Move</span><b>${GAGE.move}</b></div><p class="quote">“${GAGE.quote}”</p></div></div><div class="grid" style="margin-top:14px"><div class="card"><h3>Attributes</h3>${Object.entries(GAGE.attributes).map(([k,v])=>`<div class="row"><span>${k}</span><span class="die">${v}</span></div>`).join("")}</div><div class="card"><h3>Physical Description</h3><p>A massive Barabel covered in old scars. His equipment is immaculate. His weapons are always clean. His armor is functional rather than intimidating.</p><p>He moves slowly. Deliberately. Like someone who survived by never wasting motion.</p></div><div class="card"><h3>Readiness</h3><p>No one gets left behind.</p><p>Check exits before the menu.</p><p>The loudest person in the room is rarely the most dangerous one.</p></div></div>`}
function combat(){view.innerHTML=`<div class="card"><h3>Combat Sheet</h3><div class="tablewrap"><table><thead><tr><th>Weapon</th><th>Damage</th><th>Skill</th><th>Range</th><th>Ammo</th><th>Roll</th></tr></thead><tbody>${GAGE.weapons.map(w=>`<tr><td><b>${w.name}</b><br><span class="muted">${w.note}</span></td><td>${w.damage}</td><td>${w.skill}</td><td>${w.range}</td><td>${w.ammo}</td><td><button class="roll primary" data-dice="${w.attackDice}" data-label="${w.name} Attack">Attack</button><button class="roll" data-dice="${w.damageDice}" data-label="${w.name} Damage">Damage</button></td></tr>`).join("")}</tbody></table></div><div class="grid" style="margin-top:14px"><button class="roll primary" data-dice="6" data-label="Dodge">Dodge 6D</button><button class="roll" data-dice="6" data-label="Physical Resistance">Physical Resistance 6D</button><button class="roll" data-dice="5" data-label="Energy Resistance">Energy Resistance 5D</button><button class="roll" data-dice="4" data-label="First Aid">First Aid 4D</button></div><div id="rollout" class="output">Roll results appear here.</div></div><div class="grid" style="margin-top:14px"><div class="card"><h3>Natural Armor</h3><div class="row"><span>Physical</span><b class="die">6D</b></div><div class="row"><span>Energy</span><b class="die">5D</b></div></div><div class="card"><h3>Movement</h3><div class="row"><span>Cautious</span><b>5 m</b></div><div class="row"><span>Normal</span><b>10 m</b></div><div class="row"><span>All-Out</span><b>20 m, no other action</b></div></div><div class="card"><h3>Flow</h3><p>Declare → Roll Skill → Compare → Damage → Resist → Wounds.</p></div></div>`;view.querySelectorAll("[data-dice]").forEach(b=>b.addEventListener("click",()=>{renderRoll(document.getElementById("rollout"),b.dataset.label,Number(b.dataset.dice));beep()}))}
function skills(){const groups={};GAGE.skills.forEach(s=>{groups[s.group]??=[];groups[s.group].push(s)});view.innerHTML=`<div class="grid">${Object.entries(groups).map(([g,ss])=>`<div class="card"><h3>${g}</h3>${ss.map(s=>`<div class="skill" data-skill="${s.name}"><div class="top"><b>${s.name}</b><span class="die">${s.value}</span></div><p class="muted">${s.desc}</p>${s.trained?'<span class="tag">Trained focus</span>':'<span class="tag">Template skill</span>'}</div>`).join("")}</div>`).join("")}</div>`;view.querySelectorAll("[data-skill]").forEach(c=>c.addEventListener("click",()=>{const s=GAGE.skills.find(x=>x.name===c.dataset.skill);pop(s.name,`<p>${s.desc}</p><p><b>Value:</b> <span class="die">${s.value}</span></p><h4>Gage uses it for:</h4><ul>${s.examples.map(e=>`<li>${e}</li>`).join("")}</ul><button id="modalRoll" class="roll primary">Roll ${s.value}</button><div id="modalOut" class="output"></div>`);document.getElementById("modalRoll").addEventListener("click",()=>{renderRoll(document.getElementById("modalOut"),s.name,s.dice,s.mod||"");beep()})}))}
function gear(){view.innerHTML=`<div class="grid">${GAGE.gear.map(i=>`<div class="gear" data-gear="${i.name}"><div class="top"><b>${i.name}</b><span class="die">${i.tag}</span></div><p class="muted">${i.desc}</p></div>`).join("")}</div>`;view.querySelectorAll("[data-gear]").forEach(c=>c.addEventListener("click",()=>{const i=GAGE.gear.find(x=>x.name===c.dataset.gear);pop(i.name,`<p><span class="tag">${i.tag}</span></p><p>${i.desc}</p><p class="quote">Gage keeps his tools clean because tools are promises.</p>`)}))}
function bio(){view.innerHTML=`<div class="grid2"><div class="card"><h3>Biography</h3><div class="bio">${GAGE.bio}</div></div><div><div class="ship-art"></div><div class="card" style="margin-top:14px"><h3>Timeline</h3><div class="timeline"><div><strong>Convoy Security</strong><br>Protecting cargo meant protecting people.</div><div><strong>The Squad</strong><br>Mercenaries to others. Family to each other.</div><div><strong>The Contract</strong><br>Paid too well. Reinforcements never came.</div><div><strong>The Party</strong><br>Not employers. His people.</div></div></div></div></div>`}
function principles(){view.innerHTML=`<div class="grid">${["Never point a weapon at someone you are not prepared to kill.","Check the exits before you check the menu.","If the medic is shooting, something has gone terribly wrong.","Do not confuse courage with impatience.","Prisoners are usually more useful than bodies.","Loyalty is not obedience. It is a choice."].map(q=>`<div class="card"><p class="quote">“${q}”</p></div>`).join("")}</div>`}
function rules(){view.innerHTML=`<div class="grid">${GAGE.rules.map(r=>`<div class="rule" data-rule="${r.title}"><h3>${r.title}</h3><p>${r.body}</p></div>`).join("")}</div>`;view.querySelectorAll("[data-rule]").forEach(c=>c.addEventListener("click",()=>{const r=GAGE.rules.find(x=>x.title===c.dataset.rule);pop(r.title,`<p>${r.body}</p>`)}))}
function party(){view.innerHTML=`<div class="grid"><div class="party-card"><h3>The Captain</h3><p class="muted">The Captain is the Captain. Advice once. After that, the decision becomes the mission.</p></div><div class="party-card"><h3>The Medic</h3><p class="muted">If the medic goes down, everyone is in trouble. Protect first.</p></div><div class="party-card"><h3>The Face</h3><p class="muted">Talkers open doors. Gage watches what comes through them.</p></div><div class="party-card"><h3>The Archaeologist</h3><p class="muted">Old places have new ways to kill you.</p></div></div>`}
function ship(){view.innerHTML=`<div class="grid2"><div class="ship-art"></div><div class="card"><h3>Party Ship</h3><p>Name open.</p><p>The ship is home, transport, liability and reason to survive.</p><div class="row"><span>Bridge</span><b>Watch exits</b></div><div class="row"><span>Cargo</span><b>Check manifests</b></div><div class="row"><span>Turrets</span><b>Gage station</b></div><div class="row"><span>Medbay</span><b>Protect</b></div></div></div>`}
function journal(){const saved=localStorage.getItem("gageJournalV03")||"";view.innerHTML=`<div class="card"><h3>Free Journal</h3><p class="muted">Session notes, contacts, debts, promises, suspicions, or things Gage never says out loud.</p><textarea id="journalText" placeholder="Session 1...">${saved}</textarea><br><button id="saveJournal" class="roll primary">Save Journal</button><span id="journalStatus" class="muted"></span></div>`;document.getElementById("saveJournal").addEventListener("click",()=>{localStorage.setItem("gageJournalV03",document.getElementById("journalText").value);document.getElementById("journalStatus").textContent=" Saved locally.";beep()})}
setView("overview");
